### PR TITLE
Add scancodes alongside keycodes 

### PR DESCRIPTION
**Pull request by CHiPs44**
As we needed to handle our own keyboard layouts (and NONUSBACKSLASH) for <https://github.com/Neotron-Compute/Neotron-Desktop-BIOS/issues/14>, I added support for scancodes alongside keycodes.

I hope this PR is well formed, as I'm a rookie in Rust and a not-so experimented developer about Github habits.

### CODE REVIEW

**Comment by lukexor** [comment]
Overall looks great! I just need to address some outdated versions in the CI first

**Comment by CHiPs44** [comment]
I reworked SDL2 scan codes to make them exhaustive as there were unused values from initial copy of Key enum.

This is in commit is <https://github.com/CHiPs44/pix-engine/commit/0d7fe305a629308f45dd7ef5993c4ebe36d0d65f> but it doesn't appear automatically in this PR?

**Comment by CHiPs44** [comment]
I hope I did not messed up history.

**Comment by lukexor** [comment]
@Mergifyio update

**Comment by lukexor** [comment]
@CHiPs44 no worries. I'm working out some new CI/CD stuff. I'll try to clean things up if they got wonky.

**Comment by lukexor** [comment]
@Mergifyio rebase

**Comment by lukexor** [comment]
@CHiPs44 Can I ask that you reset back to 0d7fe305a629308f45dd7ef5993c4ebe36d0d65f and try a fresh merge of main? Something seems wrong with the commits and git can't figure it out.

If you haven't done so already, try this:

```sh
# Change to `git@github.com:lukexor/pix-engine.git` if you use SSH keys instead of HTTPS
git remote add upstream https://github.com/lukexor/pix-engine.git
git merge upstream main
```

**Pull request merged**
